mode = "monitor" # "monitor" | "scan"
[scan]
# file name of masscan json output 
input = ""
# rate in servers per second
rate = 10
[monitor]
# rate in servers per second
rate = 30

[conditions]
    [conditions.version]
    exclude = ["1.8.9"]
    include = ["1.94"]
        [conditions.version.regex]
        exclude = ['1\.\d\.3']
        include = []
    # https://wiki.vg/Protocol_version_numbers
    [conditions.protocol]
    exclude = [129, "129"]